"use client"
import Image from "next/image";

export default function Main() {

  return (
    <>

      <main
        className=
        {`
          z-[1]
          w-[100%]
          bg-[yellow]
          flex
          flex-1
          items-center
          justify-center
          `}
      >
        <div
          className=
          {`
            w-[95%]
            h-[90%]
            bg-[skyblue]
            rounded-[20px]
            flex
            justify-center
            shadow-2xl
            shadow-gray-500
            `}
        >
          <div
            className=
            {`
              flex
              flex-col
              w-[80%]
              h-[100%]
              bg-[green]
            `}
          >
            <div
              className=
              {`
                flex
                flex-row
                w-[100%]
                h-[30%]
                bg-[blue]
                my-auto
              `}
            >
              <div
                className=
                {`
                  w-[100%]
                  h-[100%]
                  bg-[red]
                  rounded-[20px]
                  mr-[20px]
                `}
              >
              </div>
              <div
                className=
                {`
                  w-[100%]
                  h-[100%]
                  bg-[red]
                  rounded-[20px]
                `}
              >
              </div>
            </div>
            <div
              className=
              {`
                flex
                flex-row
                w-[100%]
                h-[20%]
                bg-[blue]
                my-auto

              `}
            >
              <div
                className=
                {`
                  w-[80%]
                  h-[100%]
                  bg-[red]
                  rounded-[20px]
                  mr-[20px]
                  `}
              >
              </div>
              <div
                className=
                {`
                  w-[20%]
                  h-[100%]
                  bg-[red]
                  rounded-[20px]
                  `}
              >
              </div>
            </div>
            <div
              className=
              {`
                flex
                flex-row
                w-[100%]
                h-[20%]
                bg-[blue]
                my-auto
                
                `}
            >
              <div
                className=
                {`
                  w-[100%]
                  h-[100%]
                  bg-[red]
                  rounded-[20px]
                  `}
              >
              </div>
            </div>
            <div
              className=
              {`
                flex
                flex-row
                w-[100%]
                h-[20%]
                bg-[blue]
                my-auto
                
                `}
            >
              <div
                className=
                {`
                  w-[50%]
                  h-[100%]
                  bg-[red]
                  rounded-[20px]
                  mr-[20px]
                  `}
              >
              </div>
              <div
                className=
                {`
                  w-[50%]
                  h-[100%]
                  bg-[red]
                  rounded-[20px]
                  mr-[20px]
                `}
              >
              </div>
              <div
                className=
                {`
                  w-[50%]
                  h-[100%]
                  bg-[red]
                  rounded-[20px]
                  `}
              >
              </div>
            </div>
          </div>
        </div>

      </main>

    </>
  )
}
