import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "../context/AppContext";
import Providers from './providers';
import Header from "@/components/Header";
import CustomCartBox from "@/components/smallCartBox";
import Footer from "@/components/Footer";

const inter = Inter({
  variable: "--font-inter", // optional
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins", // optional
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased w-[100%] h-screen `}
      >
        <Providers>
          <AppContextProvider>
            <div
              className=
              {`
                z-[1]
                relative
                flex
                flex-col
                font-inter
                text-[var(--myTextColorNormal)]
              `}
            >
              <Header />
              <CustomCartBox />
              {children}
              <Footer />
            </div>
          </AppContextProvider>
        </Providers>
      </body>
    </html>
  );
}
